{
    "name": "Canalocio Importer (Integrated Logic)",
    "version": "17.0.1.0.0",
    "summary": "Import products from Canalocio CSV feed with integrated logic",
    "category": "Connetor",
    "author": "Binhex",
    "depends": [
        "base",
        "product",
        "stock",
        "queue_job",
        "account",
        "sale",
        "connector_importer",
        "connector",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/import_source_canal_view.xml",
        "data/import_source_data.xml",
        "data/import_backend_data.xml",
        "data/import_type_data.xml",
        "data/import_recordset_data.xml",
        "data/import_tag_data.xml",
        "data/ir_cron_data.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
    "external_dependencies": {"python": ["requests", "Pillow"]},
}
